const express = require('express');
const students = require('../student.json');
const route = express.Router();
const StudentController = require('../controllers/StudentController');
route.get('/students',StudentController.getStudents);
route.get('/students/:Rollno',StudentController.getStudentByRollno);
route.post('/add/student',StudentController.addStudent);
route.put('/update/student/:Rollno',StudentController.updateStudent);
route.delete('/delete/student/:Rollno', StudentController.deleteStudent );
module.exports = route;