const express = require('express');
const students = require('../student.json');
const route = express.Router();
const StudentController = require('../controllers/StudentController');
route.get('/students', (req, res) => { StudentController.getStudents(req, res); })
route.get('/students/:Rollno', (req, res) => { StudentController.getStudentByRollno(req, res) });
route.post('/add/student', (req, res) => { StudentController.addStudent(req, res) });
route.put('/update/student/:Rollno', (req, res) => { StudentController.updateStudent(req, res) });
route.delete('/delete/student/:Rollno', (req, res) => { StudentController.deleteStudent(req, res) });
module.exports = route;